version: "3.0"
services:
  db:
    container_name: "Shop_Bot"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - bin_volume:/var/lib/postgresql/data/
    env_file:
      - .env

    ports:
      - "5434:5432"
    networks:
      - custom
  db_test:
    container_name: "Shop_Bot_Test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=BinanceAPITest
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_PORT=5436
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "5436:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  bin_volume: